inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/*'
    - 'spec/acceptance/fixtures/**/*'
    - 'spec/unit/fixtures/**/*'
    - 'vendor/gems/**/*'
