#!/bin/bash
set -e

cd "$(dirname "$0")/.."
echo "Heres some output"
docker build -t entitlements-github-plugin -f spec/acceptance/Dockerfile.entitlements-github-plugin .
docker run -w "/data/entitlements" entitlements-github-plugin bash -c "script/test"
