name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.1.2', '3.1.4', '3.2.2', '3.2.3', '3.3.0', '3.3.1' ]

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # pin@v1.318.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test -d -k
